name: Deploy Kubernetes Agents

on:
  workflow_run:
    workflows: ["infra-plan"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: OIDC

      - name: Set kubeconfig
        run: |
          az aks get-credentials \
            --resource-group vionx-core \
            --name vionx-aks \
            --overwrite-existing

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f terraform/platform/kubernetes/bootstrap.yaml
          kubectl apply -f terraform/platform/kubernetes/eox-agent.yaml
